/* Run: node test-game.cjs — no dependencies or network. */
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const story=require('./story.js');
const {ClinicGame,observations,questions}=require('./engine.js');
const expected={O1:['A','“잠깐” 단속반'],O2:['B','퇴근 응원단'],O3:['B','내 시간 지킴이'],O4:['A','휴식 알림이'],O5:['C','첫마디 도우미'],Q1:['A','점심시간 수호자'],Q2:['B','저녁시간 지킴이'],Q3:['C','내 편 같은 원장님']};
let paths=0;
const endings=new Set(),cards=new Set(),lengths=[];
for(const o of observations)for(const q of questions)for(const selected of [o,q]){
  const g=new ClinicGame();
  assert.equal(g.choose(o),false);assert.equal(g.result(),null);
  assert.equal(g.start(),true);assert.equal(g.phase,'observe');
  assert.equal(g.exchange.player,null);assert.equal(g.exchange.patient,story.opening);
  assert.equal(g.start(),false,'no duplicate starts during a conversation');
  assert.deepEqual(g.available(),observations);assert.equal(g.choose('Q1'),false);
  let renderedChars=story.opening.length;
  const first=g.choiceText(o);
  assert.equal(first,story.items[o].prompt);assert.equal(g.choose(o),true);
  assert.equal(g.phase,'question');assert.deepEqual(g.exchange,{player:first,patient:story.items[o].reply});
  renderedChars+=g.exchange.player.length+g.exchange.patient.length;
  assert.deepEqual(g.available(),questions);
  const second=g.choiceText(q);assert.equal(second,story.items[q].prompt);assert.equal(g.choose(q),true);
  assert.equal(g.phase,'connect');assert.deepEqual(g.exchange,{player:second,patient:story.items[q].reply});
  renderedChars+=g.exchange.player.length+g.exchange.patient.length;
  assert.deepEqual(g.available(),[o,q]);
  const unavailable=Object.keys(expected).find(id=>![o,q].includes(id));
  assert.equal(g.choiceText(unavailable),null);assert.equal(g.choose(unavailable),false,'unheard topics cannot be selected');
  if(selected.startsWith('O'))assert.ok(g.choiceText(selected).startsWith('아까'),'returning to an earlier topic must be explicit');
  const last=g.choiceText(selected);assert.equal(last,story.items[selected].followupPrompt);
  assert.equal(g.choose(selected),true);assert.equal(g.phase,'ending','third choice goes straight to the ending');
  assert.deepEqual(g.exchange,{player:last,patient:story.items[selected].lastLine});
  renderedChars+=g.exchange.player.length+g.exchange.patient.length;
  assert.deepEqual(g.available(),[]);assert.equal(g.choose(selected),false);
  const r=g.result();assert.equal(r.id,selected);assert.equal(r.ending,expected[selected][0]);assert.equal(r.nickname,expected[selected][1]);
  assert.ok(r.description&&r.shareHeadline&&r.lastLine);
  endings.add(r.ending);cards.add(r.shareHeadline);lengths.push(renderedChars);
  assert.equal(g.start(true),true);assert.deepEqual(g.previous,{observation:o,question:q,selected});
  assert.equal(g.observation,null);assert.equal(g.question,null);assert.equal(g.selected,null);assert.equal(g.phase,'observe');
  assert.deepEqual(g.exchange,{player:null,patient:story.replayOpening});
  paths++;
}
assert.equal(paths,30);assert.equal(endings.size,3);assert.equal(cards.size,8);
for(const item of Object.values(story.items)){
  assert.ok(item.reply.length<=55,'first reply must fit a short exchange');
  assert.ok(item.lastLine.length<=55,'last reply must fit a short exchange');
  assert.ok(!/척추|골반|진단|치료|증상|문진/.test([item.prompt,item.reply,item.followupPrompt,item.lastLine].join(' ')),'medical explanations stay out of main dialogue');
}
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const css=fs.readFileSync(path.join(__dirname,'style.css'),'utf8');
const app=fs.readFileSync(path.join(__dirname,'app.js'),'utf8');
for(const file of ['story.js','engine.js','app.js'])new vm.Script(fs.readFileSync(path.join(__dirname,file),'utf8'),{filename:file});
for(const m of html.matchAll(/(?:src|href)="(?!https?:|#)([^"?]+)[^"]*"/g))assert.ok(fs.existsSync(path.join(__dirname,m[1])),`missing ${m[1]}`);
for(const m of css.matchAll(/url\(['"]?([^)'"?]+)['"]?\)/g))assert.ok(fs.existsSync(path.join(__dirname,m[1])),`missing ${m[1]}`);
for(const m of app.matchAll(/(?:sheet|background)\.src='([^']+)'/g))assert.ok(fs.existsSync(path.join(__dirname,m[1])),`missing ${m[1]}`);
assert.ok(!/maximum-scale|user-scalable=no/.test(html));
assert.ok(!/fetch\(|XMLHttpRequest|sendBeacon|localStorage|sessionStorage/.test(app));
assert.ok(html.includes('id="my-line"')&&html.includes('class="role-bar"'));
assert.ok(app.includes('나 · 원장님')&&app.includes('class="dialogue-name patient">최대리'));
console.log(JSON.stringify({pathsVerified:paths,endingTypes:endings.size,distinctShareCards:cards.size,choicesPerRound:3,extraDialogueClicks:0,shownQuestionMatchesSelectedButton:true,earlierTopicTransitionsExplicit:true,replayVerified:true,averageDialogueCharacters:Math.round(lengths.reduce((a,b)=>a+b,0)/lengths.length),syntaxAndAssets:'PASS',browserTesting:'not performed'},null,2));
