import assert from 'node:assert/strict';
import { readFile, access } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const html = await readFile(resolve(root, 'index.html'), 'utf8');
const app = await readFile(resolve(root, 'app.mjs'), 'utf8');
const ids = new Set(Array.from(html.matchAll(/\bid="([^"]+)"/g), match => match[1]));
for (const match of app.matchAll(/\$\('([^']+)'\)/g)) assert.ok(ids.has(match[1]), `missing DOM id: ${match[1]}`);
for (const match of html.matchAll(/(?:src|href)="(\.\/[^"?#]+)"/g)) await access(resolve(root, match[1]));
assert.match(app, /three@0\.186\.0\/build\/three\.module\.js/);
assert.match(app, /cannon-es@0\.20\.0\/dist\/cannon-es\.js/);
assert.match(html, /움직이는 말랑 분절/);
assert.match(html, /몸이 버틴다고, 중심이 맞는 것은 아닙니다/);
assert.match(html, /척추가 분절별로 중심을 잡고/);
assert.match(html, /게임적으로 단순화한 표현/);
assert.doesNotMatch(html, /조이스틱|발판을 눌러|20초 생존/);
assert.doesNotMatch(html, /측풍|바람이 불어|경사가 변합니다/);
assert.doesNotMatch(app, /hazardWarning|hazardStart|baseSlope/);
assert.doesNotMatch(html, /진료비\s*할인|치료\s*쿠폰|척추\s*나이|교정\s*필요\s*점수/);
const parent = await readFile(resolve(root, '..', 'index.html'), 'utf8');
assert.match(parent, /href="center-balance\/"/);
assert.match(parent, /center-balance\/assets\/mascot\.svg/);
console.log('mallow-tower static checks passed');
